import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const generalsans = localFont({
  src: [
    {
      path: './fonts/zeno/GeneralSans-Variable.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/zeno/GeneralSans-VariableItalic.woff2',
      weight: '400',
      style: 'italic',
    },
  ],
  variable: '--font-generalsans',
})

const arsenal = localFont({
  src: [
    {
      path: './fonts/zeno/Arsenal-Bold.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-arsenal',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${arsenal.variable} ${generalsans.variable} font-sans`}>
        {children}
      </body>
    </html>
  )
}
